//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1_Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int aboutID { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public string imageurl { get; set; }
    }
}
