//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1_Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int educationID { get; set; }
        public string title { get; set; }
        public string educationDate { get; set; }
        public string subtitle { get; set; }
        public string description { get; set; }
    }
}
