//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1_Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int profileID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string github { get; set; }
        public string imageurl { get; set; }
        public string mapLocation { get; set; }
    }
}
